### ISSUE TITLE
运行python版本错误

### ISSUE THREAD

**Issue by AcademicDog** [society765/yys-auto-yuhun#4]
已注册dll，win10系统，python 3.7.2 x64

运行报错如下
![TIM截图20190415223019](https://user-images.githubusercontent.com/21212008/56140998-89b8c480-5fce-11e9-85dd-fd8b7e9b8dd4.png)

查找错误编号众说纷纭，有说装32位python，又有说进程没有关闭导致。

**Comment by AcademicDog** [comment]
已解决，python必须是32位

**Comment by xwang233** [comment]
多谢反馈！因为我的python是32位的 我没有注意到有这个问题存在

**Comment by FatherHat** [comment]
我出现类似的问题，装的64windows ,32位的python
![QQ截图20190505143622](https://user-images.githubusercontent.com/50133803/57189578-f75b6f00-6f42-11e9-888c-79b7b7ccbf4f.png)

**Comment by FatherHat** [comment]
也注册了dll
![QQ截图20190505143710](https://user-images.githubusercontent.com/50133803/57189607-19ed8800-6f43-11e9-88ad-c467dfdcbc83.png)

**Comment by FatherHat** [comment]
啊哈，尴尬的发现我好想装的是64位的python

**Comment by xwang233** [comment]
@FatherHat 你好，你第一行的输出显示的是64位 Python。你可以尝试下安装32位Python然后重新运行脚本。

**Comment by FatherHat** [comment]
@society765 谢谢，我也发现了这个问题。。。我更换为32位python就可以运行了。

**Comment by Innei** [comment]
32位也无法运行
```python
python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
Traceback (most recent call last):
  File "C:\Users\yiny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, '无效的类字符串', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./py_onmyoji_yuhun.py", line 157, in <module>
    ts = win32com.client.Dispatch("ts.tssoft")
  File "C:\Users\yiny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\yiny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\yiny\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, '无效的类字符串', None, None)
```

**Comment by xwang233** [comment]
@Innei 可能存在的问题是你没有注册 TSPlug.dll 插件，请参考 https://github.com/society765/yys-auto-yuhun#%E5%B7%B2%E7%9F%A5%E5%AD%98%E5%9C%A8%E7%9A%84%E9%97%AE%E9%A2%98
